version: "3"

services:

  front:
    image: node:16.13.2-alpine
    command: yarn dev
    ports:
      - ${FRONT_PORT}:3000
    environment:
      # yarn devの出力先がコンテナ自身になるように設定が必要
      HOST: '0.0.0.0'
    volumes:
      - ./front:/var/www/front
    working_dir: /var/www/front
    depends_on:
      - nginx
        
  nginx:
    image: nginx:1.21.1-alpine
    ports:
      - ${NGINX_PORT}:80
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./api/public:/var/www/api/public
    depends_on:
      - api

  api:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    volumes:
      - ./api:/var/www/api
      # phpに設定を変更したい時にコメントイン
      # - ./docker/php/php.ini:/usr/local/etc/php/conf.d/php.ini
    working_dir: /var/www/api
    depends_on:
      - db

  db:
    image: mysql:8.0
    ports:
      - ${DB_PORT}:3306
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      TZ: 'Asia/Tokyo'